### ISSUE TITLE
stack-update() will not correctly parse template within zsh

### ISSUE THREAD

**Issue by BTheunissen** [realestate-com-au/bash-my-aws#108]
https://github.com/realestate-com-au/bash-my-aws/blob/simpler/lib/stack-functions#L104

This line will not correctly parse the template file argument into a local variable. It will always appear that no template file parameter has been passed. I have narrowed this down to how zsh (at least in this instance) will interact with passing a string of space-seperated words into a function.

Going to look more into this but interesting to find, and might be a root cause for zsh weirdness.

I have tried to reproduce in /bin/bash and the function appears to work as expected.

**Comment by mbailey** [comment]
Thanks for posting.

Unfortunately (your zsh users) I don't use zsh or claim to support it.

If you find a simple fix for that please reopen and I'll consider updating.
