### ISSUE TITLE
override params?

### ISSUE THREAD

**Issue by fantapop** [realestate-com-au/bash-my-aws#109]
I'm looking for a way to allow passing a file as parameters but also being able to override certain parameters or setting certain parameters as required on the command line.  An example of this that when I spin up a vpc, I want to specify the CIDR block it uses.  I'd like to use a parameter file such as dev.json to describe all the fields required in dev but each user who wants a custom dev environment needs to have a separate cider block.

I was envisioning something like:

```stack-create example-test --override "VpcCidr=10.2.0.0"```

which would use all values from example.json except would override VpcCidr with the passed value.

Or an even better user experience would be if the VpcCidr wasn't in example.json but the stack new that this was a required field for it to be created so it prompted the user for a value.
```
stack-create example-test
please enter required value for parameter "VpcCidr":
10.2.0.0
creating stack ... 
```

Would you consider supporting this?  Or is there a different recommended way to acheive something similar?

thanks

**Comment by mbailey** [comment]
I'm pretty excited about the `deploy` function in AWSCLI.

It does a create-or-update (good for scripts, dangerous at command line when you are logged into wrong account).

It also enables TAB completion for the template name.

The parameter-overrides functionality is great. It defaults to UsePreviousValue for everything. :-)

```
aws cloudformation deploy                                        \
  --stack-name example-stack                                   \
  --template-file cloudformation/example-stack.yml \
  --parameter-overrides "VpcCidr=10.2.0.0"
```

I will possibly be adding a stack-deploy function in future but the AWSCLI function is pretty damn usable on it's own! :-)

**Comment by fantapop** [comment]
sweet. Thanks for the heads up.
