### ISSUE TITLE
Cloudformation functions run with excessive permissions

### ISSUE THREAD

**Issue by dushankw** [realestate-com-au/bash-my-aws#110]
The `stack` functions do not follow the principal of least privilege.

Here is an example https://github.com/realestate-com-au/bash-my-aws/blob/master/lib/stack-functions#L91

Any stack deployed with the `stack-create` function is deployed with the permission set `CAPABILITY_NAMED_IAM` regardless of whether it is actually needed.

This may have been decided for convenience, however it creates an issue. People who pull a 3rd party stack from the internet and deploy it without reading in detail may end up creating IAM users or cross-account roles that are controlled by a 3rd party without noticing.

Proposal: Add an option to control this behaviour and default to not running with any capabilities.

**Comment by dushankw** [comment]
We can also avoid additional complexity in the `stack-update` function by having it first check what capabilities the target stack was deployed with and then running with the corresponding capability set.

EG: `aws cloudformation describe-stacks --stack-name WHATEVER --output text | grep CAPABILITIES` tells us what we would need to know...

**Comment by jonhiggs** [comment]
That's a good idea and yes, I think I remember adding that for convenience.

**Comment by dushankw** [comment]
Mike and I are going to do a PR very soon.

**Comment by jonhiggs** [comment]
I'll give it a review if you like.

**Comment by dushankw** [comment]
:boom: https://github.com/realestate-com-au/bash-my-aws/pull/111
