### ISSUE TITLE
plugins.d

### ISSUE THREAD

**Issue by jonhiggs** [realestate-com-au/bash-my-aws#13]
Consider moving the functions into a directory named `plugins.d/`. This makes it clear to users that bash-my-aws is intended to be extended and makes it obvious how it's done.

**Comment by ajc** [comment]
Apologies for being overly philosophical, but from my somewhat remote standpoint, this feels like unnecessary layering. Shell functions are shell functions. Why do we need to call them "plugins"?

(and what open source project isn't intended to be extended, really?)

**Comment by jonhiggs** [comment]
My reasoning stemmed from Mike's idea that we don't intend to ever include everything, it's up to the user to add the functionality that they desire. Our responsibility is to add the scaffolding and instruction to make it easy for users to create what they need. He used the Nagios as an example of a similar model.

A plugins.d directory expresses that sentiment with nothing more than the creation of a directory as a breadcrumb. It's intuitive. When I see a directory named plugins, it immediately tells me that this is intended to be extended and if the directory name ends in ".d" it tells me that that is where I put my stuff and it will automatically get sourced in.

**Comment by jonhiggs** [comment]
I don't think this is relevant anymore.
