### ISSUE TITLE
things that we want

### ISSUE THREAD

**Issue by mbailey** [realestate-com-au/bash-my-aws#16]
show list of all my stacks
* filter that list (grep)
show asgs for stack(s)
show instances associated with asgs

rds_arn()

$INSTANCE_OUTPUT

everythings() --tags

__bma_read_input()
* do all input parsing

output
* --output json

**Comment by jonhiggs** [comment]
--output json works (--json as shorthand)

**Comment by jonhiggs** [comment]
I think we have also done "show list of all my stacks, filter that list (grep) show asgs for stack(s) show instances associated with asgs"

**Comment by jonhiggs** [comment]
I'm not sure what "everythings() --tags" means anymore. Can that be speced up and a ticket raised if we still want it?

**Comment by jonhiggs** [comment]
I think the "do all input parsing" thing is done too.
