### ISSUE TITLE
simple way to display AWSCLI command for function

### ISSUE THREAD

**Issue by mbailey** [realestate-com-au/bash-my-aws#18]

**Comment by jonhiggs** [comment]
use the __bma_exec_aws() function with the --debug switch on the command line and you should (if everything is working) get the aws command.

I want to add some tests to confirm that it's all good.

**Comment by jonhiggs** [comment]
This has been moved into the hooks branch to avoid slowing down the release of version 1.

**Comment by jonhiggs** [comment]
#63 could help with this
