### ISSUE TITLE
clean up personal documents

### ISSUE THREAD

**Issue by jonhiggs** [realestate-com-au/bash-my-aws#28]
Need to migrate doc/jons_notes.txt and doc/mikes_notes.md into issues or something else maybe.

**Comment by jonhiggs** [comment]
I've cleaned up jons_notes.txt

**Comment by mbailey** [comment]
removed docs/mikes_notes

**Comment by jonhiggs** [comment]
Can we also clean up notes.md? I don't think they belong in the repo. Maybe they should become issues. @mbailey

**Comment by jonhiggs** [comment]
I've cleaned this up.
