### ISSUE TITLE
move lib/*-functions ./

### ISSUE THREAD

**Issue by mbailey** [realestate-com-au/bash-my-aws#34]
The directory root is now clean and simple. Yay.
I'm still very drawn to the idea of putting the resource-functions scripts in the top level dir.
This would mean they're listed when someone hits the project page or checks out directory.
I feel like this would make them more accessible.
What do you think @jonhiggs ?

```
bash-my-aws(dev)$ ls
LICENSE   Makefile  README.md bin       doc       lib       test
```

**Comment by jonhiggs** [comment]
I feel that it's self-explanatory and well documented the way that it is. If you feel strongly I won't object to changing it.
