### ISSUE TITLE
Using aliases doesn't work.

### ISSUE THREAD

**Issue by jonhiggs** [realestate-com-au/bash-my-aws#43]
We must accept resources at the end of a line.

If you use an alias, you want your switches at the start and arguments at the end. 

``` ShellSession
$ alias instances="instances --query 'Reservations[].Instances[][InstanceId]'"
$ instances i-aa500674
I will die
```

That fails because the resource must come before the --query switch. This needs to be changed for aliases to work correctly.

**Comment by mbailey** [comment]
Going to remove most switches (to simplify)
