### ISSUE TITLE
functions that only operate on first resource are failing

### ISSUE THREAD

**Issue by mbailey** [realestate-com-au/bash-my-aws#49]
```local stack=$(__bma_read_resources ${inputs} | awk '{print $1}')```

__bma_read_resources returns multiline output so we should probably replace awk with head

**Comment by jonhiggs** [comment]
Awk is stripping out the extras which we will still need to do. 'head -n1' at the end of the chain will do it.

**Comment by mbailey** [comment]
I thought __bma_read_imputs() strips them out with:

awk '{ print $1 }'

**Comment by mbailey** [comment]
d613b5854c5bb2b30eeb1852b2f788db7fdc8bf7
