### ISSUE TITLE
README.md update?

### ISSUE THREAD

**Issue by fazlearefin** [realestate-com-au/bash-my-aws#5]
Hey Mike,
I completely missed the `instance-functions` until I was about to create my own functions using `aws ` CLI. Maybe have some pointer about the `instance-functions` file in your `README.md`?

**Comment by mbailey** [comment]
It comes down to time constraints.

instance-functions are about to get an upgrade (ssh gets better)
Also close to deciding to make cloudformation-functions use instance_ssh

**Comment by fazlearefin** [comment]
Cool, ta
