### ISSUE TITLE
fix the broken tests

### ISSUE THREAD

**Issue by jonhiggs** [realestate-com-au/bash-my-aws#51]
@mbailey, you've committed some stuff at 3cc323c07e1e8474048e481f7cadcd2213ae1e74 and it's broken tests. I had a little look but I'm going to leave it to you to fix. :)

**Comment by jonhiggs** [comment]
I fixed the test because I needed them working before I could do something else. @mbailey can you review that it's not broken what ever reason it was that made you want to change it in the first place. :)

**Comment by mbailey** [comment]
Sorry about that. I had changed __bma_read_stdin() to not strip newlines.
__bma_read_inputs can does that by not quoting its output:

```bash
echo $(__bma_read_stdin) $@
```

I'm happy to leave it as single line.
