### ISSUE TITLE
cf_asg_instances function has strange behavior

### ISSUE THREAD

**Issue by fazlearefin** [realestate-com-au/bash-my-aws#56]
Hi Mike,

Just stumbled across a peculiar issue with `cf_asg_instances` function. When I do a `cf_asg_instances some_stack` on a CFN stack and all the ec2 instances in the stack is powered off, `cf_asg_instances some_stack` returns every single ec2 instance in the AWS account. And when I do a `cf_asg_instance_ssh some_stack`, I get ssh-ed into an ec2 instance that does not even belong to the stack at all.

Happy to provide more details if needed.

**Comment by jonhiggs** [comment]
Cheers. @mbailey fixed that a few days ago in #40 which in on the dev branch. You're welcome to try it out. It's very close to release.

**Comment by fazlearefin** [comment]
Yes, it worked. I noticed that functions have completely different names in the `dev` branch. Is that how it is going to be in the upcoming release? The new naming convention does make more sense though.
