### ISSUE TITLE
stack-instances fails to trim '.json'

### ISSUE THREAD

**Issue by mtibben** [realestate-com-au/bash-my-aws#67]
$ stack-instances payments-apps-2015-11-18-11-32.json

A client error (ValidationError) occurred when calling the DescribeStackResources operation: 1 validation error detected: Value 'payments-apps-2015-11-18-11-32.json' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*

**Comment by mbailey** [comment]
Before bash-my-aws completed stack name args by querying AWS for stack list, command completion happened (very quickly!) using file completion. You could just tab complete using the template file name (including the .json extension) and bash-my-aws would know what you mean.

The new bash-completion obviates this need however I'd like to keep the underlying behaviour.

Done
