### ISSUE TITLE
Support CloudFormation templates/params stored as YAML? :thumbsdown:"

### ISSUE THREAD

**Issue by mbailey** [realestate-com-au/bash-my-aws#89]
Some people I like like viewing/editing their CloudFormation as YAML.

https://github.com/buildkite/buildkite-aws-stack/blob/master/buildkite-elastic.yml

It's cute but it's not usable with bash-my-aws or AWSCLI without being converted to JSON first.

I am yet to meet anyone who has setup their editor to convert between them automatically so there is a lot of YAMLized CloudFormation being checked into Git.

Do we want to add support for reading YAML files to stack-functions:
- stack-create()
- stack-update()
- stack-diff()

I don't feel comfortable doing this because while many people prefer reading and writing YAML, I think it's better for people to use a standard format for storing CloudFormation. 

Thoughts?

**Comment by grahamlyons** [comment]
Now that AWS supports YAML natively perhaps this issue is much easily addressed?
