### ISSUE TITLE
Add function of list all volumes an remove inactive volumes

### ISSUE THREAD

**Issue by cbweixin** [realestate-com-au/bash-my-aws#9]
bash-my-aws is a great project and save me a lot of typing and time during my daily routine job, but I think there could be more enhancements, for ex, the function to list all volumes, search volume and delete volum.

sometimes, there would be a case a lot of volumes got created and but not deleted on time, so you would see something like this:
![image](https://cloud.githubusercontent.com/assets/1326906/9210088/11bb56ea-402f-11e5-9e82-2fc017c90ae5.png)
and this:
![image](https://cloud.githubusercontent.com/assets/1326906/9210116/37ff4ffa-402f-11e5-8529-1d754027ff8b.png)

most of volumes are at a 'available' status rather than 'in-use' status. those volumes could be safely removed. 

So  I want to add some functionality as below:
1. Add a function to list all volumes, and could also sort volumes by category.
2. remove all volums

I will fork you project and send a pull request later. thanks a lot.

**Comment by mbailey** [comment]
Thanks for the kind words.

By all means go ahead and create volume functions. Just so you know, yesterday I had a discussion with some colleagues and we've come up with an improved convention for functions that list and act on resources. I wouldn't wait though as it will be easy to refactor if you keep the functions simple.
